# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators.kubedb.com
  labels:
    app: kubedb
webhooks:
- name: proxysql.validators.kubedb.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/validators.kubedb.com/v1alpha1/proxysqlvalidators
    caBundle: not_ca
  rules:
    - apiGroups: ["kubedb.com"]
      apiVersions: ["*"]
      resources: ["proxysqls"]
      operations: ["CREATE", "UPDATE", "DELETE"]
  failurePolicy: Fail
  sideEffects: None
---
# register to intercept kubedb CRD creates / updates
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutators.kubedb.com
  labels:
    app: kubedb
webhooks:
- name: proxysql.mutators.kubedb.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/mutators.kubedb.com/v1alpha1/proxysqlmutators
    caBundle: not_ca
  rules:
    - apiGroups: ["kubedb.com"]
      apiVersions: ["*"]
      resources: ["proxysqls"]
      operations: ["CREATE", "UPDATE"]
  failurePolicy: Fail
  sideEffects: None
